name: Go Build & Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Vet (static analysis)
        run: go vet ./...
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
      - name: Test with coverage
        run: go test -cover ./...
      # Generates a BoM and uploads it to OWASP Dependency Track
      # Only runs on main branch or version tags (v*)
      - name: Generates BoM and upload to OWASP DTrack
        id: riskscoreFromDT
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses:  VinnterAB/dependency-tracker-action@v0.0.5
        with:
          url: ${{ vars.DTRACK_URL }}
          key: '${{ secrets.DTRACK_KEY }}'
          language: 'golang'
          version: ${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          action: 'upload'
          isLatest: ${{ github.ref == 'refs/heads/main' }}
      # Show the risk score output
      - name: Get the output time
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: echo "The risk score of the project is ${{ steps.riskscoreFromDT.outputs.riskscore }}"
      # Upload BoM for pull requests
      - name: Upload BoM for PR
        id: prUpload
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
        uses: VinnterAB/dependency-tracker-action@v0.0.5
        with:
          url: ${{ vars.DTRACK_URL }}
          key: '${{ secrets.DTRACK_KEY }}'
          language: 'golang'
          version: PR-${{ github.event.pull_request.number }}
          action: 'upload'
          isLatest: 'false'
      # Delete BoM when PR is closed
      - name: Delete BoM for closed PR
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: VinnterAB/dependency-tracker-action@v0.0.5
        with:
          url: ${{ vars.DTRACK_URL }}
          key: '${{ secrets.DTRACK_KEY }}'
          language: 'golang'
          version: PR-${{ github.event.pull_request.number }}
          action: 'delete'
